import "@/styles/globals.css";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
// import "" "fonts/sans"

import { Inter } from "next/font/google";
// import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "@/trpc/react";
import { ThemeProvider } from "./_components/theme-provider";
import MainLayout from "./_components/main-layout";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
  weight: ["300", "400", "500", "600", "700"],
});

// const fontFarsi = localFont({
//   src: "./IRAN_SemiBold.woff2",
//   variable: "--font-farsi",
//   display: "swap",
// });

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    // <html lang="en" className={`${GeistSans.variable}`}>
    <html suppressHydrationWarning lang="fr" className={` ${inter.variable}`}>
      <body className="font-sans">
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <TRPCReactProvider>
            <MainLayout>{children}</MainLayout>
            <ReactQueryDevtools />
          </TRPCReactProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
